# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'iOS Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for iOS Example

  pod 'RxSwift', '5.1.1'
  pod 'RxPhotos', :path => '../'

end
